services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.dev
    image: frontend:latest
    ports:
      - "3000:3000"
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.dev
    image: backend:latest
    ports:
      - "8000:8000"
    