services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile.prod
    image: frontend:latest
    ports:
      - "3003:3000"
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile.prod
    image: backend:latest
    ports:
      - "8003:8000"